### ISSUE TITLE
aws-lambda: aws_lambda.Function.from_function_arn returns FunctionBaseProxy instead of IFunction object

### ISSUE THREAD

**Issue by arutz12** [aws/jsii#4657] opened 2024-10-10 04:37 UTC
### Describe the bug

CDK: 2.161.1
Python: 3.9.18 (and 3.11.7)
aws-solutions-constructs.aws-eventbridge-lambda: 2.72.0

`aws_lambda.Function.from_function_arn` returns _FunctionBaseProxy_ instead of _IFunction_ as documented.
Therefore the object fails when typechecked in the **aws-solutions-constructs.aws-eventbridge-lambda** module:

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

Function returns object of type _IFunction_ as documented.

### Current Behavior

Function returned _FunctionBaseProxy_ object.

### Reproduction Steps

```
#!/usr/bin/env python3

from constructs import Construct
import aws_cdk as cdk
from aws_cdk import aws_lambda, aws_events
from aws_solutions_constructs import aws_eventbridge_lambda

class LambdaFunctionTest(cdk.Stack):

    def __init__(self, scope: Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        function_arn = f"arn:aws:lambda:us-east-1:1234567890:function:LambdaFunctionName"

        event_lambda = aws_lambda.Function.from_function_arn(self, "LambdaFunction", function_arn)

        event_to_lambda = aws_eventbridge_lambda.EventbridgeToLambda(
            scope=self,
            id="EventToLambda",
            event_rule_props=aws_events.RuleProps(),
            existing_lambda_obj=event_lambda
        )


app = cdk.App()
LambdaFunctionTest(app, "LambdaFunctionTest")
app.synth()


```

### CDK CLI Version

2.161.1

### Node.js Version

v18.17.1

### OS

KDE neon 6.2 (Ubuntu 22.04)

### Language

Python

### Language Version

3.9.18 (also 3.11.7)

### Other information

Running _synth_ on the code:

```
Traceback (most recent call last):
  File "/tmp/lambda_test/app.py", line 26, in <module>
    LambdaFunctionTest(app, "LambdaFunctionTest")
  File "/tmp/lambda_test/.venv/lib/python3.9/site-packages/jsii/_runtime.py", line 118, in __call__
    inst = super(JSIIMeta, cast(JSIIMeta, cls)).__call__(*args, **kwargs)
  File "/tmp/lambda_test/app.py", line 17, in __init__
    event_to_lambda = aws_eventbridge_lambda.EventbridgeToLambda(
  File "/tmp/lambda_test/.venv/lib/python3.9/site-packages/jsii/_runtime.py", line 118, in __call__
    inst = super(JSIIMeta, cast(JSIIMeta, cls)).__call__(*args, **kwargs)
  File "/tmp/lambda_test/.venv/lib/python3.9/site-packages/aws_solutions_constructs/aws_eventbridge_lambda/__init__.py", line 214, in __init__
    props = EventbridgeToLambdaProps(
  File "/tmp/lambda_test/.venv/lib/python3.9/site-packages/aws_solutions_constructs/aws_eventbridge_lambda/__init__.py", line 281, in __init__
    check_type(argname="argument existing_lambda_obj", value=existing_lambda_obj, expected_type=type_hints["existing_lambda_obj"])
  File "/tmp/lambda_test/.venv/lib/python3.9/site-packages/aws_solutions_constructs/aws_eventbridge_lambda/__init__.py", line 164, in check_type
    return typeguard.check_type(argname=argname, value=value, expected_type=expected_type) # type:ignore
  File "/tmp/lambda_test/.venv/lib/python3.9/site-packages/typeguard/__init__.py", line 757, in check_type
    checker_func(argname, value, expected_type, memo)
  File "/tmp/lambda_test/.venv/lib/python3.9/site-packages/typeguard/__init__.py", line 558, in check_union
    raise TypeError('type of {} must be one of ({}); got {} instead'.
TypeError: type of argument existing_lambda_obj must be one of (aws_cdk.aws_lambda.Function, NoneType); got aws_cdk.aws_lambda._FunctionBaseProxy instead

```

**Comment by kmonihen** [comment] 2024-10-11 14:47
https://github.com/aws/constructs/releases/tag/v10.3.2
They added a workaround to the `constructs` package in the latest release. I confirmed constructs 10.3.2 installs `typeguard~=2.13.3` and the code synths without error now.

It looks like they will address this issue in the constructs repo, but if you need more code that fails with typeguard on 4.3.0 I was using this code to replicate the error:

```
from aws_cdk import App, Stack
from aws_cdk import aws_lambda, aws_s3
from aws_cdk import aws_s3_notifications as s3_notify

app = App()
stack = Stack(app, "bucket-stack")

bucket = aws_s3.Bucket(stack, "Bucket")

bucket.add_event_notification(
    event=aws_s3.EventType.OBJECT_CREATED,
    dest=s3_notify.LambdaDestination(
        aws_lambda.Function.from_function_arn(
            stack,
            "ObjectCreatedLambda",
            "arn:aws:lambda:us-west-2:460106496004:function:ObjectCreatedLambda-qQkkxlUaClaJ",
        )
    ),
)

app.synth()
```

**Comment by mrgrain** [comment] 2024-10-11 14:58
Thanks @kmonihen More reproduction code is always helpful. Your example should work indeed because `LambdaDestination()` expects and `IFunction` and `Function.from_function_arn()` returns an `IFunction`.

It does seem that the old version of `typeguard` incorrectly does NOT catch the type-missmatch in the original report. Because the types of `EventbridgeToLambda()` and `Function.from_function_arn()` are just not compatible.

**Comment by arutz12** [comment] 2024-10-11 15:18
> Hey @arutz12 Thanks for reporting this issue. While there are some current ongoings with jsii in this area (like @khushail confirmed), I don't think the issue you are running into is that.
> 
> `aws-solutions-constructs.aws-eventbridge-lambda` defines `existing_lambda_obj` as `lambda.Function` (see: https://docs.aws.amazon.com/solutions/latest/constructs/aws-eventbridge-lambda.html#pattern-properties)
> 
> However you are trying to give it the result of `from_function_arn`, which is an `IFunction`. **That is never going to work.** Not sure if `aws-solutions-constructs` could offer something that fits your needs better.

So even if the issue mentioned above (proper return values for from_function_arn) is fixed this complex construct can only be implemented in the same stack (as most of aws-solutions' modules), so I have to look for another solution in my case.
Thanks @mrgrain for the clarification.

**Comment by mrgrain** [comment] 2024-10-11 15:36
Yes, I that's about it. You can try reaching out to [aws-solutions-constructs](https://github.com/awslabs/aws-solutions-constructs) if they would be willing to support your use case.

Closing this. The open jsii issue is tracked here https://github.com/aws/jsii/issues/4658

**Closed by mrgrain** 2024-10-11 15:36 UTC
Labels: bug, effort/medium, response-requested, p1
