### ISSUE TITLE
Make jsii libraries thread-safe in Java

### ISSUE THREAD

**Issue by fha-aws** [aws/jsii#4377] opened 2023-12-17 17:30 UTC
### Describe the feature

Please update jsii so that multiple threads can build CDK templates at the same time. It appears that there is a ton of static singleton objects being used by jsii which is not thread-safe, which results in errors such as these.

`Exception in thread "Thread-1" software.amazon.jsii.JsiiException: Malformed object reference. Expecting $jsii.byref
	at software.amazon.jsii.JsiiObjectRef.parse(JsiiObjectRef.java:52)
	at software.amazon.jsii.JsiiClient.createObject(JsiiClient.java:91)
	at software.amazon.jsii.JsiiEngine.createNewObject(JsiiEngine.java:458)`

Related issue - https://github.com/aws/jsii/issues/685

### Use Case

We have multiple tasks that need to dynamically generate templates at runtime. The workaround at the moment is synchronize these tasks using a lock before interacting with any new CDK objects. This is frustrating as the process for facilitating these actions are severely bottle-necked by only having one thread have the ability to create a template at a time.

### Proposed Solution

Proposed solution is to have the jsii team remove all static singletons being used internally by the library and replace them with standalone objects for facilitating the creation of CDK apps and other entities.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.115.0

### Environment details (OS name and version, etc.)

macOs Ventura 13.5.2

**Comment by mrgrain** [comment] 2024-02-19 10:27
Duplicate of #4311

**Closed by mrgrain** 2024-02-19 10:27 UTC
Labels: feature-request, needs-triage
