### ISSUE TITLE
release 1.15.0 makes cdk synth radically slow

### ISSUE THREAD

**Issue by ThomasSteinbach** [aws/jsii#2284] opened 2020-11-27 10:15 UTC
### Affected Languages

- [ ] `TypeScript` or `Javascript`
- [x] `Python`
- [x] `Java`
- [ ] .NET (`C#`, `F#`, ...)

### General Information
* **JSII Version:** 1.15.1
* **Platform:**     Python

```
sh-4.2# uname -a
Linux 454d0ce8e2e4 5.4.39-linuxkit #1 SMP Fri May 8 23:03:06 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
sh-4.2# python3 -V -V
Python 3.7.9 (default, Aug 27 2020, 21:59:41)
[GCC 7.3.1 20180712 (Red Hat 7.3.1-9)]
```

### What is the problem?

When upgrading to `pip3 install --upgrade jsii==1.15.0` the synthesis with CDK up to 10 times slower. Some of our pipeline jobs take now 80 minutes instead of 8.

We have a complex app.py with loads of stacks and also loads of lookups to the AWS account during synthesis. Normally it takes "only" 10 seconds to synthesize the CFN scripts. However as often as I switch between jsii==1.14.1 and jsii==1.15.0 I get the same result, that the synthesis takes much much longer. This is independent from the AWS version I use (client and library).

```
sh-4.2# date && python3 app.py && date
Fri Nov 27 09:29:22 UTC 2020
Fri Nov 27 09:29:32 UTC 2020
sh-4.2# pip3 install --upgrade jsii
...
      Successfully uninstalled jsii-1.14.1
Successfully installed jsii-1.15.0
sh-4.2# date && python3 app.py && date
Fri Nov 27 09:29:52 UTC 2020
Fri Nov 27 09:31:54 UTC 2020
```

### Verbose Log

Because of privacy reasons I dont want to provide verbose logs. However I made a diff of both verbose logs before and after upgrading to jsii==1.15.1 and there were just a couple and no spectacular differences:

* modules workdir
  * before: /tmp/jsii-kernel-7tSAAx
  * after: /tmp/jsii-kernel-WXbuZ8
* the cdk.out*-directory

Both log files are of same length and same content, except the module wordir and the cdk out dir.

**Comment by RomainMuller** [comment] 2020-11-30 16:13
Hey @ThomasSteinbach - thanks for reporting this.

Can you give us a little more info on your app & environment, so we have an easier time trying to reproduce your performance issue?
- How many stacks does your app have? How many resources per stack (on average / ballpark)?
- What version of `node` is your system using? (`node -v` and/or `node -p process.versions`)

**Comment by RomainMuller** [comment] 2020-11-30 16:20
The delta between both releases is: [`v1.14.1...v1.15.0`](https://github.com/aws/jsii/compare/v1.14.1...v1.15.0).

If I were to throw a wild guess at which changes could cause the performance issues:
- **VERY LIKELY** https://github.com/aws/jsii/commit/1453ed34736917b54cfc212b2fa5e381714d1654 (https://github.com/aws/jsii/pull/2238)
  + In particular, the 50ms `sleep` that was introduced when recovering from `EAGAIN`
     * https://github.com/aws/jsii/blob/1453ed34736917b54cfc212b2fa5e381714d1654/packages/%40jsii/runtime/lib/sync-stdio.ts#L56
      * https://github.com/aws/jsii/blob/1453ed34736917b54cfc212b2fa5e381714d1654/packages/%40jsii/runtime/lib/sync-stdio.ts#L102
- **LESS LIKELY** https://github.com/aws/jsii/commit/29b226281c71e62049f72a9418011925e17dc615 (https://github.com/aws/jsii/pull/2247)

**Comment by RomainMuller** [comment] 2020-11-30 16:27
Actually in light of the previous guess, I would be really interested in the output of `node -p process.versions`, in particular the `v8` entry therein.

We should be able to easily validate my suspicion by making a new build without the `sleep` statements (trading time for CPU thrashing - which is effectively what we had been doing before).

Ideally, we'd want to wait for "50 ms or until the stream becomes readable, whichever happens first", but I don't know of a way to make this in the synchronous context we must stay in there...

**Comment by ThomasSteinbach** [comment] 2020-11-30 17:17
Hi @RomainMuller ,
since we started with CDK 1.43 we are using node 12.13.1 as suggested in the documentation.

Within this app we have defined +100 stacks (~about, because some stacks were created depending on the number of top level elements of a yaml file) with at least 50 resources. Mostly we create ssm parameters, but due to limitations of parameters/resources per stack, we split some stacks programatically into more. Besides ssm parameters we mainly deploy plain EC2 instances (in a for-loop), A- and CNAMe-records, S3 buckets, ... nothing special.

```
node -p process.versions
{
  node: '12.13.1',
  v8: '7.7.299.13-node.16',
  uv: '1.33.1',
  zlib: '1.2.11',
  brotli: '1.0.7',
  ares: '1.15.0',
  modules: '72',
  nghttp2: '1.39.2',
  napi: '5',
  llhttp: '1.1.4',
  http_parser: '2.8.0',
  openssl: '1.1.1d',
  cldr: '35.1',
  icu: '64.2',
  tz: '2019c',
  unicode: '12.1'
}
```

**Comment by Ophirr33** [comment] 2020-12-01 00:51
Witnessing similar behavior in a java-cdk project:
```
node -p process.versions
{
  node: '12.18.0',
  v8: '7.8.279.23-node.37',
  uv: '1.37.0',
  zlib: '1.2.11',
  brotli: '1.0.7',
  ares: '1.16.0',
  modules: '72',
  nghttp2: '1.41.0',
  napi: '6',
  llhttp: '2.0.4',
  http_parser: '2.9.3',
  openssl: '1.1.1g',
  cldr: '37.0',
  icu: '67.1',
  tz: '2019c',
  unicode: '13.0'
}
```
It's running so slowly that I was convinced it was hanging or that I was offline for some reason.

**Comment by slotnick** [comment] 2020-12-01 01:12
Just confirming that we are seeing much slower behavior with 1.15.0--our deployment process went from 1 hour to 1.5 hours, a 50% increase. Would greatly appreciate a speedy resolution.

**Comment by RomainMuller** [comment] 2020-12-02 14:03
So #2298 is a candidate solution (the issue is somewhat delicate to reproduce as it appears to disproportionately affect some specific platforms).

Once the PR validation has gone through, I'll provide instructions on how you can use the PR build artifacts in order to verify whether this actually solves the problem for you or not, so I can determine if this is the proper solution, or if I should simply drop the `sleep` calls until we have a better solution.

**Comment by RomainMuller** [comment] 2020-12-02 14:04
@all-contributors add @ThomasSteinbach, @Ophirr33 and @slotnick for bugs

**Comment by ThomasSteinbach** [comment] 2020-12-02 16:57
@RomainMuller that would be nice. If "the PR validation artifacts" are a installable pypi package, I should be able to easyly check the behavior within my docker container.

**Comment by slotnick** [comment] 2020-12-02 18:18
Happy to test the changes once you send the instructions. Thanks for jumping on this!

**Comment by RomainMuller** [comment] 2020-12-03 09:13
Here it is:

1. Download the [release-package.zip](https://github.com/aws/jsii/files/5634936/release-package.zip) file.
2. Unzip that
3. Depending on the language
   * In the `python` directory, you'll find a `.whl` package you should be able to `pip install` into your app
   * The `java` directory is a Maven repository (and the JAR file is down under there if it's faster to point at it)
   * The `dotnet` directory contains NuGet packages that can be installed

**Comment by RomainMuller** [comment] 2020-12-03 09:19
You can verify the above ZIP file using this signature file (it would be named `release-package.zip.asc` if GitHub supported the `.asc` extension): [release-package.zip.txt](https://github.com/aws/jsii/files/5634973/release-package.zip.txt)

Using the `gpg` command, once both files are in the same directory, you can verify using `gpg --verify release-package.zip.txt release-package.zip`

**Comment by srinivasreddych** [comment] 2020-12-05 21:32
Hello Team. we started seeing our build stages taking ~20minutes, which used to take max of 5minutes. For now, we have downgraded jsii from 1.15 to 1.14.

**Comment by slotnick** [comment] 2020-12-05 23:35
I can confirm that the patch resolved the performance issue in our Python CDK project.

**Comment by RomainMuller** [comment] 2020-12-07 09:27
@slotnick thank you for confirming! I'll get this merged & released as soon as possible then!

**Closed** 2020-12-07 11:52 UTC
Labels: bug, language/python, needs-reproduction, p1

**Comment by ThomasSteinbach** [comment] 2020-12-07 12:10
Sorry @RomainMuller for the late reply, but I also confirm the performance gains.

```
Successfully installed jsii-1.15.0
sh-4.2# date && python3 app.py && date
Mon Dec  7 12:03:30 UTC 2020
Mon Dec  7 12:06:07 UTC 2020
...
Successfully installed jsii-1.15.1-dev.2298.0
sh-4.2# date && python3 app.py && date
Mon Dec  7 12:07:51 UTC 2020
Mon Dec  7 12:08:02 UTC 2020
```

The synthesis now takes in my example 11 seconds instead of 157 seconds. Thank you very much for the improvement.
