### ISSUE TITLE
java: error implementing IPrincipal in Java

### ISSUE THREAD

**Issue by rix0rrr** [aws/jsii#266] opened 2018-10-16 13:16 UTC
Posting on behalf of @leepa: 

```java
       class Foo implements IPrincipal {
            @Override
            public PolicyPrincipal getPrincipal() {
                return new ArnPrincipal("arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity " + webDistribution.getId());
            }

            @Override
            public void addToPolicy(PolicyStatement policyStatement) {

            }

            @Override
            public void attachInlinePolicy(Policy policy) {

            }

            @Override
            public void attachManagedPolicy(String s) {

            }
        }

        bucket.grantRead(new Foo());
```

Leads to

```
[jsii-kernel] creating objref for PolicyStatement {
  valueOrFunction: undefined,
  displayName: undefined,
  action: [ 's3:GetObject*', 's3:GetBucket*', 's3:List*' ],
  principal: [],
  resource:
   [ '${Token[CDNBucketB6E01002.Arn.185]}', '${Token[TOKEN.192]}' ],
  condition: {},
  effect: 'Allow' }
< {"callback":{"cookie":"public void fishing.lee.infrastructure.ContentDistribution$1Foo.addToPolicy(software.amazon.awscdk.services.iam.PolicyStatement)","cbid":"jsii::callback::10573","invoke":{"objref":{"$jsii.byref":"Object@10572"},"method":"addToPolicy","args":[{"$jsii.byref":"@aws-cdk/aws-iam.PolicyStatement@10574"}]}}}
> {"complete":{"cbid":"jsii::callback::10573","err":"argument type mismatch"}}
< {"error":"argument type mismatch","stack":"Error: argument type mismatch\n    at i (/private/var/folders/_f/ny7cgfhx1cq4j37p6148qw1x9tqrxj/T/jsii-java-runtime4773234722066897123/jsii-runtime.js:1:74795)\n    at t.KernelHost.callbackHandler (/private/var/folders/_f/ny7cgfhx1cq4j37p6148qw1x9tqrxj/T/jsii-java-runtime4773234722066897123/jsii-runtime.js:1:74878)\n    at t.Kernel.kernel.n.Kernel.e [as callbackHandler] (/private/var/folders/_f/ny7cgfhx1cq4j37p6148qw1x9tqrxj/T/jsii-java-runtime4773234722066897123/jsii-runtime.js:1:74493)\n    at Object.value (/private/var/folders/_f/ny7cgfhx1cq4j37p6148qw1x9tqrxj/T/jsii-java-runtime4773234722066897123/jsii-runtime.js:1:85711)\n    at Bucket.grant (/private/var/folders/_f/ny7cgfhx1cq4j37p6148qw1x9tqrxj/T/jsii-kernel-XNt2xX/node_modules/@aws-cdk/aws-s3/lib/bucket.js:224:18)\n    at Bucket.grantRead (/private/var/folders/_f/ny7cgfhx1cq4j37p6148qw1x9tqrxj/T/jsii-kernel-XNt2xX/node_modules/@aws-cdk/aws-s3/lib/bucket.js:137:14)\n    at _wrapSandboxCode (/private/var/folders/_f/ny7cgfhx1cq4j37p6148qw1x9tqrxj/T/jsii-java-runtime4773234722066897123/jsii-runtime.js:1:80519)\n    at t.Kernel._wrapSandboxCode (/private/var/folders/_f/ny7cgfhx1cq4j37p6148qw1x9tqrxj/T/jsii-java-runtime4773234722066897123/jsii-runtime.js:1:91696)\n    at a._ensureSync (/private/var/folders/_f/ny7cgfhx1cq4j37p6148qw1x9tqrxj/T/jsii-java-runtime4773234722066897123/jsii-runtime.js:1:80496)\n    at t.Kernel._ensureSync (/private/var/folders/_f/ny7cgfhx1cq4j37p6148qw1x9tqrxj/T/jsii-java-runtime4773234722066897123/jsii-runtime.js:1:91213)\n    at t.Kernel.invoke (/private/var/folders/_f/ny7cgfhx1cq4j37p6148qw1x9tqrxj/T/jsii-java-runtime4773234722066897123/jsii-runtime.js:1:80441)\n    at t.KernelHost.processRequest (/private/var/folders/_f/ny7cgfhx1cq4j37p6148qw1x9tqrxj/T/jsii-java-runtime4773234722066897123/jsii-runtime.js:1:75232)\n    at t.KernelHost.run (/private/var/folders/_f/ny7cgfhx1cq4j37p6148qw1x9tqrxj/T/jsii-java-runtime4773234722066897123/jsii-runtime.js:1:74921)\n    at e.processRequest (/private/var/folders/_f/ny7cgfhx1cq4j37p6148qw1x9tqrxj/T/jsii-java-runtime4773234722066897123/jsii-runtime.js:1:74947)\n    at t.KernelHost.processRequest (/private/var/folders/_f/ny7cgfhx1cq4j37p6148qw1x9tqrxj/T/jsii-java-runtime4773234722066897123/jsii-runtime.js:1:75686)\n    at t.KernelHost.run (/private/var/folders/_f/ny7cgfhx1cq4j37p6148qw1x9tqrxj/T/jsii-java-runtime4773234722066897123/jsii-runtime.js:1:74921)\n    at e.processRequest (/private/var/folders/_f/ny7cgfhx1cq4j37p6148qw1x9tqrxj/T/jsii-java-runtime4773234722066897123/jsii-runtime.js:1:74947)\n    at t.KernelHost.processRequest (/private/var/folders/_f/ny7cgfhx1cq4j37p6148qw1x9tqrxj/T/jsii-java-runtime4773234722066897123/jsii-runtime.js:1:75686)"}
Exception in thread "main" software.amazon.jsii.JsiiException: argument type mismatch
Error: argument type mismatch
    at i (/private/var/folders/_f/ny7cgfhx1cq4j37p6148qw1x9tqrxj/T/jsii-java-runtime4773234722066897123/jsii-runtime.js:1:74795)
    at t.KernelHost.callbackHandler (/private/var/folders/_f/ny7cgfhx1cq4j37p6148qw1x9tqrxj/T/jsii-java-runtime4773234722066897123/jsii-runtime.js:1:74878)
    at t.Kernel.kernel.n.Kernel.e [as callbackHandler] (/private/var/folders/_f/ny7cgfhx1cq4j37p6148qw1x9tqrxj/T/jsii-java-runtime4773234722066897123/jsii-runtime.js:1:74493)
    at Object.value (/private/var/folders/_f/ny7cgfhx1cq4j37p6148qw1x9tqrxj/T/jsii-java-runtime4773234722066897123/jsii-runtime.js:1:85711)
    at Bucket.grant (/private/var/folders/_f/ny7cgfhx1cq4j37p6148qw1x9tqrxj/T/jsii-kernel-XNt2xX/node_modules/@aws-cdk/aws-s3/lib/bucket.js:224:18)
....
```

Looks like the `addToPolicy()` callback throws a type error, which is then propagated to JavaScript and returned back in the original Java call.

But why?

**Comment by fulghum** [comment] 2019-08-13 15:52
@RomainMuller – can you help us understand if this is still an issue?

**Comment by RomainMuller** [comment] 2019-08-28 08:46
I was not able to reproduce this uses - I attempted the following code (using the latest CDK API, as the one mentioned above has changed somewhat since this issue was filed):

```java
package com.myorg;

import com.google.common.collect.ImmutableMap;

import software.amazon.awscdk.core.App;
import software.amazon.awscdk.core.Stack;
import software.amazon.awscdk.services.iam.ArnPrincipal;
import software.amazon.awscdk.services.iam.IPrincipal;
import software.amazon.awscdk.services.iam.PolicyStatement;
import software.amazon.awscdk.services.iam.PrincipalPolicyFragment;
import software.amazon.awscdk.services.s3.Bucket;

public class HelloApp {
    public static void main(final String argv[]) {
        final App app = new App();
        final Stack stack = new Stack(app, "ReproStack");

        final Bucket bucket = new Bucket(stack, "Bucket");
        bucket.grantRead(new CustomPrincipal());

        // required until https://github.com/aws/jsii/issues/456 is resolved
        app.synth();
    }
}

class CustomPrincipal implements IPrincipal {
    @Override
    public IPrincipal getGrantPrincipal() {
        return new ArnPrincipal("arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity *");
    }

    @Override
    public Boolean addToPolicy(PolicyStatement statement) {
        return false;
    }

    @Override
    public String getAssumeRoleAction() {
        return "sts:AssumeRole";
    }

    @Override
    public PrincipalPolicyFragment getPolicyFragment() {
        return new PrincipalPolicyFragment(ImmutableMap.of());
    }
}
```

It synthesized to exactly what I expected and did not cause errors. At this point I am assuming the bug was fixed since the issue was filed!

Resolving now. Please re-open if you hit that problem again (in which case I'd appreciate if you can provide a minimally modified version of my repro above that triggers the issue).

**Closed by RomainMuller** 2019-08-28 08:46 UTC
Labels: language/java, needs-repro
