### ISSUE TITLE
JSII9000 Encountered use of module that is not declared in "dependencies" or "peerDependencies"

### ISSUE THREAD

**Issue by gocapa** [aws/jsii#4414] opened 2024-02-02 13:10 UTC
### Describe the bug

I am using a package @XXXX as a dependency that is not prepared to use JSII so I added it to bundledDependencies. 

import { RefTypes } from '@XXXX';

The Error: 
src/builder/validator.ts:15:20 - error JSII9000: Encountered use of module that is not declared in "dependencies" or "peerDependencies": "@XXXX"

### Expected Behavior

Should not stop the JSII process because of this because the package is in dependencies.

### Current Behavior

src/builder/validator.ts:15:20 - error JSII9000: Encountered use of module that is not declared in "dependencies" or "peerDependencies": "@XXXX"

### Reproduction Steps

npm run build

### Additional Information/Context

  JSII Config
  
  "jsii": {
    "outdir": "dist",
    "versionFormat": "full",
    "targets": {
      "python": {
        "distName": "X",
        "module": "X"
      },
      "java": {
        "package": "X",
        "maven": {
          "groupId": "X",
          "artifactId": "X"
        }
      }
    },
    "tsc": {
      "outDir": "dist-tsc",
      "rootDir": "src"
    }
  },

### SDK version used

5.3.7 (build e512679), typescript 5.3.3

### Environment details (OS name and version, etc.)

MAC Node.js v18.12.0

**Comment by TimothyJones** [comment] 2024-02-11 06:26
Are you exporting anything from that module? This error will happen if JSii is trying to translate a type from the bundled package (since it can't).

**Comment by mrgrain** [comment] 2024-02-19 10:26
@gocapa can you provide the complete package.json? Any deps in `bundledDependencies` must also be in `dependencies`. Plus like @TimothyJones said, you likely cannot reexport anything from bundled deps.

**Comment by mrgrain** [comment] 2024-04-09 11:01
No reproduction. Closing. 

Like stated before, bundled deps also need to be defined as `dependencies`.

**Closed by mrgrain** 2024-04-09 11:01 UTC
Labels: bug
