### ISSUE TITLE
Java/DotNet: abstract members are not marked as such on their .NET and Java representations.

### ISSUE THREAD

**Issue by rix0rrr** [aws/jsii#1011] opened 2019-11-19 10:47 UTC
## :bug: Bug Report

In this code:

https://github.com/rix0rrr/jsii-test-drive/blob/master/java/extends-abstract-class/src/main/java/com/myorg/MyCode.java﻿

The subclass of `Code` is not complete. It is missing an implementation of `public abstract readonly isInline: boolean`.

This class should have been needed to be marked abstract, but it it isn't.

### Impact to CDK
* Abstract members have an implementation in the generated **.NET** and **Java** code, allowing	classes extending those to omit implementation of some (or all) of the abstract members. While the resulting code compiles, it may fail at run-time due to the missing implementations.
* _Workaround_: when extending abstract classes, consult the [TypeScript API reference] to identify all abstract members of the extended type, and make sure to implement all of those. The members will be made abstract in a subsequent release of the CDK for Java and .NET, <u>**which will break invalid implementations**</u>.

[TypeScript API Reference]: https://docs.aws.amazon.com/cdk/api/latest/typescript/api/index.html

**Comment by rix0rrr** [comment] 2019-11-19 14:36
This feels wrong-- the `abstract`-ness of a member should be mirrored into the JSII bindings.

**Comment by nija-at** [comment] 2019-11-19 14:38
Same problem affecting c# - https://github.com/rix0rrr/jsii-test-drive/blob/master/dotnet/serverless/src/Serverless/Program.cs

**Comment by rix0rrr** [comment] 2019-11-19 14:39
Accessing the "abstract" member results in a predictable JSII exception:

```
Unhandled exception. Amazon.JSII.Runtime.JsiiException: Got 'undefined' for non-optional instance of {"abstract":true,"docs":{"stability":"stable","summary":"The name of the function."},"immutable":true,"locationInModule":{"filename":"lib/function-base.ts","line":148},"name":"functionName","overrides":"@aws-cdk/aws-lambda.IFunction","type":{"primitive":"string"}}
   at Amazon.JSII.Runtime.Services.Client.TryDeserialize[TResponse](String responseJson)
   at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()
   at Amazon.JSII.Runtime.Services.Client.Send[TRequest,TResponse](TRequest requestObject)
   at Amazon.JSII.Runtime.Services.Client.Get(GetRequest request)
   at Amazon.JSII.Runtime.Services.Client.Get(ObjectReference objectReference, String property)
   at Amazon.JSII.Runtime.Deputy.DeputyBase.<>c__DisplayClass9_0`1.<GetInstanceProperty>b__0(IClient client)
   at Amazon.JSII.Runtime.Deputy.DeputyBase.GetPropertyCore[T](JsiiPropertyAttribute propertyAttribute, Func`2 getFunc)
   at Amazon.JSII.Runtime.Deputy.DeputyBase.GetInstanceProperty[T](String propertyName)
   at Amazon.CDK.AWS.Lambda.FunctionBase.get_FunctionName()
   at Serverless.Program.Main(String[] args) in /Users/nija/workplace/cdk/jsii-test-drive/dotnet/serverless/src/Serverless/Program.cs:line 36
```

**Comment by RomainMuller** [comment] 2019-11-26 17:28
This is actually a duplicate of #240

**Closed** 2019-12-19 08:58 UTC
Labels: bug, language/dotnet, language/java, p1, status/in-progress
