### ISSUE TITLE
Cross Platform Error Stack Traces

### ISSUE THREAD

**Issue by skorfmann** [aws/jsii#1840] opened 2020-07-31 09:48 UTC
### Affected Languages

- [ ] `TypeScript` or `Javascript`
- [x] `Python`
- [x] `Java` (haven't checked it)
- [x] .NET (`C#`, `F#`, ...) (haven't checked it)

### General Information
* **JSII Version:** 
* **Platform:**     

* [ ] I may be able to implement this feature request

### Description

When errors are occurring in one of the generated language targets, it's not possible by the stack trace to see where the error was originating from. See this stack trace for an AWS CDK app:

```json
        "/foo/foo/Resource": [
          {
            "type": "aws:cdk:logicalId",
            "data": "foo6445C170",
            "trace": [
              "new Bucket (/private/var/folders/zl/z8nc41qs7010qsfngfc_z1zc0000gn/T/jsii-kernel-ZbnPBD/node_modules/@aws-cdk/aws-s3/lib/bucket.js:387:26)",
              "/Users/sebastian/projects/cdk/tmp/foo/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7915:49",
              "Kernel._wrapSandboxCode (/Users/sebastian/projects/cdk/tmp/foo/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:8388:20)",
              "Kernel._create (/Users/sebastian/projects/cdk/tmp/foo/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7915:26)",
              "Kernel.create (/Users/sebastian/projects/cdk/tmp/foo/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7659:21)",
              "KernelHost.processRequest (/Users/sebastian/projects/cdk/tmp/foo/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7439:28)",
              "KernelHost.run (/Users/sebastian/projects/cdk/tmp/foo/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7377:14)",
              "Immediate._onImmediate (/Users/sebastian/projects/cdk/tmp/foo/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7380:37)",
              "processImmediate (internal/timers.js:456:21)"
            ]
          }
        ]
```

It looks similar for `cdktf` apps, see this issue for more context: https://github.com/hashicorp/terraform-cdk/issues/131

### Proposed Solution

It would be good to see a reference to the code in the respective language (e.g. Python), rather than having JS stack traces only.

**Comment by RomainMuller** [comment] 2020-10-07 10:29
This is a duplicate of #47

**Closed by RomainMuller** 2020-10-07 10:29 UTC
Labels: effort/large, feature-request, needs-triage, p2
